name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, labeled]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    if: contains(github.event.pull_request.labels.*.name, 'ai-review')
    uses: Geniova-Technologies/.github/.github/workflows/ai-pr-review.yml@main
    with:
      prompt_url: "https://planning-gamexp-default-rtdb.europe-west1.firebasedatabase.app/globalConfigs/prompts/-OkmjTOQ-jErBg5JgXlI.json"
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
